memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  mmio_GPIO_USB_CRC_SCTIMER_PWM:
    base_addr: 0x1c000000
    permissions: rw
    size: 0x28000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  sram:
    base_addr: 0x2000000
    permissions: rwx
    size: 0x8000
  text:
    base_addr: 0x0
    file: ../../01-access-modeling-for-fuzzing/pw-discovery/LPC1549/basic_exercises.bin
    is_entry: true
    permissions: r-x
    size: 0x800000
mmio_models:
  constant:
    pc_00000ab2_mmio_40040008:
      access_size: 0x4
      addr: 0x40040008
      pc: 0xab2
      val: 0x1
    pc_00000abe_mmio_40040008:
      access_size: 0x4
      addr: 0x40040008
      pc: 0xabe
      val: 0x4
    pc_00000b78_mmio_4007419c:
      access_size: 0x4
      addr: 0x4007419c
      pc: 0xb78
      val: 0x1
    pc_00000bbc_mmio_400741ac:
      access_size: 0x4
      addr: 0x400741ac
      pc: 0xbbc
      val: 0x1
  passthrough:
    pc_000001fa_mmio_400740c4:
      access_size: 0x4
      addr: 0x400740c4
      init_val: 0x0
      pc: 0x1fa
    pc_00000292_mmio_1c002000:
      access_size: 0x4
      addr: 0x1c002000
      init_val: 0x0
      pc: 0x292
    pc_0000080a_mmio_400f8064:
      access_size: 0x4
      addr: 0x400f8064
      init_val: 0x0
      pc: 0x80a
    pc_0000086e_mmio_40038000:
      access_size: 0x4
      addr: 0x40038000
      init_val: 0x0
      pc: 0x86e
    pc_0000088e_mmio_40038000:
      access_size: 0x4
      addr: 0x40038000
      init_val: 0x0
      pc: 0x88e
    pc_0000088e_mmio_40038004:
      access_size: 0x4
      addr: 0x40038004
      init_val: 0x0
      pc: 0x88e
    pc_0000088e_mmio_40038008:
      access_size: 0x4
      addr: 0x40038008
      init_val: 0x0
      pc: 0x88e
    pc_0000088e_mmio_4003800c:
      access_size: 0x4
      addr: 0x4003800c
      init_val: 0x0
      pc: 0x88e
    pc_0000088e_mmio_40038010:
      access_size: 0x4
      addr: 0x40038010
      init_val: 0x0
      pc: 0x88e
    pc_0000088e_mmio_40038014:
      access_size: 0x4
      addr: 0x40038014
      init_val: 0x0
      pc: 0x88e
    pc_0000088e_mmio_40038018:
      access_size: 0x4
      addr: 0x40038018
      init_val: 0x0
      pc: 0x88e
    pc_0000088e_mmio_4003801c:
      access_size: 0x4
      addr: 0x4003801c
      init_val: 0x0
      pc: 0x88e
    pc_0000088e_mmio_40038020:
      access_size: 0x4
      addr: 0x40038020
      init_val: 0x0
      pc: 0x88e
    pc_0000088e_mmio_40038024:
      access_size: 0x4
      addr: 0x40038024
      init_val: 0x0
      pc: 0x88e
    pc_0000088e_mmio_40038028:
      access_size: 0x4
      addr: 0x40038028
      init_val: 0x0
      pc: 0x88e
    pc_0000088e_mmio_4003802c:
      access_size: 0x4
      addr: 0x4003802c
      init_val: 0x0
      pc: 0x88e
    pc_0000088e_mmio_40038030:
      access_size: 0x4
      addr: 0x40038030
      init_val: 0x0
      pc: 0x88e
    pc_0000088e_mmio_40038034:
      access_size: 0x4
      addr: 0x40038034
      init_val: 0x0
      pc: 0x88e
    pc_0000088e_mmio_40038038:
      access_size: 0x4
      addr: 0x40038038
      init_val: 0x0
      pc: 0x88e
    pc_0000088e_mmio_4003803c:
      access_size: 0x4
      addr: 0x4003803c
      init_val: 0x0
      pc: 0x88e
    pc_000008d0_mmio_40040020:
      access_size: 0x4
      addr: 0x40040020
      init_val: 0x0
      pc: 0x8d0
    pc_000008d2_mmio_40074128:
      access_size: 0x4
      addr: 0x40074128
      init_val: 0x0
      pc: 0x8d2
    pc_0000093c_mmio_40040000:
      access_size: 0x4
      addr: 0x40040000
      init_val: 0x0
      pc: 0x93c
    pc_000009e8_mmio_400740c8:
      access_size: 0x4
      addr: 0x400740c8
      init_val: 0x0
      pc: 0x9e8
    pc_000009f6_mmio_40074048:
      access_size: 0x4
      addr: 0x40074048
      init_val: 0x0
      pc: 0x9f6
    pc_000009fe_mmio_40074048:
      access_size: 0x4
      addr: 0x40074048
      init_val: 0x0
      pc: 0x9fe
    pc_00000a48_mmio_40040000:
      access_size: 0x4
      addr: 0x40040000
      init_val: 0x0
      pc: 0xa48
    pc_00000b2a_mmio_40074208:
      access_size: 0x4
      addr: 0x40074208
      init_val: 0x0
      pc: 0xb2a
    pc_00000b4a_mmio_40074208:
      access_size: 0x4
      addr: 0x40074208
      init_val: 0x0
      pc: 0xb4a
    pc_00000b6c_mmio_40074208:
      access_size: 0x4
      addr: 0x40074208
      init_val: 0x0
      pc: 0xb6c
    pc_00000b8c_mmio_40074208:
      access_size: 0x4
      addr: 0x40074208
      init_val: 0x0
      pc: 0xb8c
    pc_00000b98_mmio_40074208:
      access_size: 0x4
      addr: 0x40074208
      init_val: 0x0
      pc: 0xb98
    pc_00000ba4_mmio_40074208:
      access_size: 0x4
      addr: 0x40074208
      init_val: 0x0
      pc: 0xba4
    pc_00000bc4_mmio_400740c4:
      access_size: 0x4
      addr: 0x400740c4
      init_val: 0x0
      pc: 0xbc4
    pc_00000bfc_mmio_400740c8:
      access_size: 0x4
      addr: 0x400740c8
      init_val: 0x0
      pc: 0xbfc
    pc_00000c08_mmio_40074048:
      access_size: 0x4
      addr: 0x40074048
      init_val: 0x0
      pc: 0xc08
    pc_00000c10_mmio_40074048:
      access_size: 0x4
      addr: 0x40074048
      init_val: 0x0
      pc: 0xc10
    pc_00000c46_mmio_1c024004:
      access_size: 0x4
      addr: 0x1c024004
      init_val: 0x0
      pc: 0xc46
    pc_00000caa_mmio_1c024004:
      access_size: 0x4
      addr: 0x1c024004
      init_val: 0x0
      pc: 0xcaa
    pc_00000cb6_mmio_1c024004:
      access_size: 0x4
      addr: 0x1c024004
      init_val: 0x0
      pc: 0xcb6
  set:
    pc_00000d62_mmio_1c002100:
      access_size: 0x4
      addr: 0x1c002100
      pc: 0xd62
      vals:
      - 0x0
      - 0x2000000
  unmodeled:
    pc_00000a08_mmio_400740d0:
      access_size: 0x4
      addr: 0x400740d0
      pc: 0xa08
    pc_00000ab8_mmio_40040014:
      access_size: 0x4
      addr: 0x40040014
      pc: 0xab8
    pc_00000c92_mmio_1c024040:
      access_size: 0x4
      addr: 0x1c024040
      pc: 0xc92
use_nvic: false
use_systick: false
use_timers: false
